#!/bin/bash

# Copyright 2019 Tad Lebeck
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEST_NAME="API REPLAY"

if [ "$#" -ne 2 ] ; then
    echo "USAGE: api_replay num"
    exit 1
fi
NUVO_VM=$1
NUM_APIS=$2

# setup the cluster
source ./fake_cluster $NUVO_VM

fake_cluster_create 1 1 1G 104857600

# fake_clusster letting me do background commands in parallel would be awesome
server_dir=$TEST_DIR/1
declare -A API_PID
date
for i in $(seq 1 $NUM_APIS) ; do
     $NUVO_VM -s ${NODE_CTRL[$server_dir]} debug-trigger --trigger nanosleep --multi-use1=0 --multi-use2=200000000 &
     API_PID[$i]=$!
done
for i in $(seq 1 $NUM_APIS) ; do
     wait ${API_PID[$i]}
done
date
# cluster tear-down is handled in finish
