#!/bin/bash

# Copyright 2019 Tad Lebeck
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEST_NAME="Crash Replay"

if [ "$#" -ne 9 ] ; then
    echo "USAGE: crash_replay nuvo_vm_cmd num_servers num_devices num_parcels parcel_size io_range io_size blk_size num_snaps"
    echo "USAGE: num servers in cluster"
    echo "USAGE: num_devices is number of devices"
    echo "USAGE: num_parcels is parcels per device"
    echo "USAGE: parcel_size is in MB"
    exit 1
fi
NUVO_VM=$1
PARAM_NUM_SERVERS=$2
PARAM_NUM_DEVICES_PER_SERVER=$3
PARAM_NUM_PARCELS=$4
PARAM_PARCEL_SIZE=$5
PARAM_IO_RANGE_MB=$6
PARAM_IO_SIZE_MB=$7
PARAM_IO_BLK_SIZE=$8
PARAM_IO_NUM_SNAPS=$9

# TODO - loop to use num snaps
size_of_parcel=$(expr $PARAM_PARCEL_SIZE \* 1024 \* 1024)
size_of_device=$(expr $PARAM_NUM_PARCELS \* $size_of_parcel + 16 \* 1024 \* 1024)
fio_size=$(expr $PARAM_IO_RANGE_MB \* 1024 \* 1024)
io_size=$(expr $PARAM_IO_SIZE_MB \* 1024 \* 1024)

# setup the cluster
source ./fake_cluster $NUVO_VM

fake_cluster_create $PARAM_NUM_SERVERS $PARAM_NUM_DEVICES_PER_SERVER $size_of_device $size_of_parcel

# now create and use a volume
ROOT_DEVICE_UUID=${DEV_UUIDS[0]}
VOL_SERVER=${DEV_SERVER[$ROOT_DEVICE_UUID]}
fake_cluster_create_vol $VOL_SERVER $ROOT_DEVICE_UUID $(expr 20 \* 1024 \* 1024 \* 1024)
VOL_UUID=${VOL_UUIDS[0]}

# add parcels to the volume
fake_cluster_grow_volume_percent $VOL_UUID 100

# ----------------------------------------------------------------------
# now I can do some test stuff
fake_cluster_export_active $VOL_UUID
NUVOVOL=$(fake_cluster_active_path $VOL_UUID)
rand_seed1=$RANDOM
fio --name=test --verify=crc32c --rw=randwrite --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed1

fake_cluster_reboot_cluster
fake_cluster_log_level 1 logger 20
fake_cluster_open_vol $VOL_UUID
fake_cluster_export_active $VOL_UUID

fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed1

# Now take a snapshot of that.
PIT1_UUID=$( uuidgen )
fake_cluster_pause_io $VOL_UUID
fake_cluster_create_pit $VOL_UUID $PIT1_UUID
fake_cluster_resume_io $VOL_UUID

# Right some more stuff.
rand_seed2=$RANDOM
fio --name=test --verify=crc32c --rw=randwrite --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed2

fake_cluster_reboot_cluster
fake_cluster_log_level 1 logger 20
fake_cluster_open_vol $VOL_UUID
fake_cluster_export_active $VOL_UUID
fake_cluster_export_pit $VOL_UUID $PIT1_UUID
PIT1=$(fake_cluster_pit_path $PIT1_UUID)
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed2
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$PIT1 --randseed $rand_seed1

fake_cluster_vol_manifest $VOL_UUID "crash_replay_1.png"

fake_cluster_debug_trigger 1 --trigger "disable_cp" --volume $VOL_UUID

for i in `seq 100 -1 1`; do
    fake_cluster_debug_trigger 1  --trigger "gc_segment" --volume $VOL_UUID --parcel-index 0 --segment-index $i
done

fake_cluster_vol_manifest $VOL_UUID "crash_replay_2.png"

fake_cluster_reboot_cluster
fake_cluster_log_level 1 logger 20
fake_cluster_open_vol $VOL_UUID
fake_cluster_export_active $VOL_UUID
fake_cluster_export_pit $VOL_UUID $PIT1_UUID
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed2
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$PIT1 --randseed $rand_seed1

fake_cluster_debug_trigger 1 --trigger "disable_cp" --volume $VOL_UUID
for i in `seq 100 -1 1`; do
    fake_cluster_debug_trigger 1  --trigger "gc_segment" --volume $VOL_UUID --parcel-index 0 --segment-index $i
done

fake_cluster_vol_manifest $VOL_UUID "crash_replay_3.png"

fake_cluster_reboot_cluster
fake_cluster_log_level 1 logger 20
fake_cluster_open_vol $VOL_UUID
fake_cluster_export_active $VOL_UUID
fake_cluster_export_pit $VOL_UUID $PIT1_UUID
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed2
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$PIT1 --randseed $rand_seed1

for i in `seq 100 -1 1`; do
    fake_cluster_debug_trigger 1  --trigger "gc_segment" --volume $VOL_UUID --parcel-index 0 --segment-index $i
done

fake_cluster_reboot_cluster
fake_cluster_log_level 1 logger 20
fake_cluster_open_vol $VOL_UUID
fake_cluster_export_active $VOL_UUID
fake_cluster_export_pit $VOL_UUID $PIT1_UUID
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL --randseed $rand_seed2
fio --name=test --verify_only --verify=crc32c --rw=randread --size=$fio_size --io_size=$io_size --ioengine=libaio --iodepth=1\
     --bs=$PARAM_IO_BLK_SIZE --direct=1 --numjobs=1 --unlink=0 --filename=$PIT1 --randseed $rand_seed1

fake_cluster_vol_manifest $VOL_UUID "crash_replay_4.png"
