#!/bin/bash

# Copyright 2019 Tad Lebeck
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEST_NAME="CUM 1044"

# setup the cluster - a small cluster with small devices for example.
source ./fake_cluster $1
num_servers=1
devices_per_server=2
size_of_device=512M
size_of_parcel=$(expr 256 \* 1024 \* 1024)
fake_cluster_create $num_servers $devices_per_server $size_of_device $size_of_parcel

# now create and use a volume
ROOT_DEVICE_UUID=${DEV_UUIDS[0]}
VOL_SERVER=${DEV_SERVER[$ROOT_DEVICE_UUID]}
fake_cluster_create_vol $VOL_SERVER $ROOT_DEVICE_UUID 1024000000
VOL_UUID=${VOL_UUIDS[0]}

# add parcels to the volume
fake_cluster_grow_volume_percent $VOL_UUID 100

# ----------------------------------------------------------------------
# now I can do some test stuff
TEMPFILE=/tmp/t$$
COPYFILE=/tmp/c$$
RANDFILE=/dev/urandom

# Build the reference file
dd if=$RANDFILE of=$TEMPFILE bs=128K count=200 2> /dev/null

# $NUVO_VM_FT_CMD -s ${NODE_CTRL[$VOL_SERVER]} log-level -m "mfst" -l 50

for N in 1 2 3 4 5
    do
        fake_cluster_vol_manifest $VOL_UUID "manifest.png"
        fake_cluster_export_active $VOL_UUID
        NUVOVOL=$(fake_cluster_active_path $VOL_UUID)
        dd if=$TEMPFILE of=$NUVOVOL bs=128K count=200 oflag=direct conv=notrunc 2> /dev/null
        sync
        fake_cluster_unexport_active $VOL_UUID
        fake_cluster_vol_manifest $VOL_UUID "manifest.png"
        fake_cluster_close_vol $VOL_UUID
        fake_cluster_open_vol $VOL_UUID
done

rm -f $TEMPFILE $COPYFILE
