#!/bin/bash
# Copyright 2019 Tad Lebeck
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEST_NAME="sequential"

# setup the cluster - a small cluster with small devices for example.
source ./fake_cluster $1
num_servers=1
devices_per_server=2
size_of_device=5G
size_of_parcel=512000000
fake_cluster_create $num_servers $devices_per_server $size_of_device $size_of_parcel

# now create and use a volume
ROOT_DEVICE_UUID=${DEV_UUIDS[0]}
VOL_SERVER=${DEV_SERVER[$ROOT_DEVICE_UUID]}
fake_cluster_create_vol $VOL_SERVER $ROOT_DEVICE_UUID 4096000000
VOL_UUID=${VOL_UUIDS[0]}

# add parcels to the volume
fake_cluster_grow_volume_percent $VOL_UUID 100

# export the active lun
fake_cluster_export_active $VOL_UUID

# ----------------------------------------------------------------------
# now I can do some test stuff
NUVOVOL=$(fake_cluster_active_path $VOL_UUID)

fio --name=write --rw=write --size=1G --ioengine=libaio --iodepth=1 --bs=128K --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL
fio --name=read --rw=read --size=1G --ioengine=libaio --iodepth=1 --bs=128K --direct=1 --numjobs=1 --unlink=0 --filename=$NUVOVOL

# Now create a file system
mkfs -t ext4 -b 4096 $NUVOVOL

fake_cluster_mount_lun $VOL_UUID

fio --name=write --rw=write --size=100M --ioengine=libaio --iodepth=1 --bs=128K --direct=1 --numjobs=1 --filename=${LUN_MOUNT_POINT[$VOL_UUID]}/fio_test
fio --name=read --rw=read --size=100M --ioengine=libaio --iodepth=1 --bs=128K --direct=1 --numjobs=1 --unlink=0 --filename=${LUN_MOUNT_POINT[$VOL_UUID]}/fio_test

# cluster tear-down is handled in finish
